/**
 * Marlin 3D打印机固件
 * 版权所有 (c) 2023 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * 基于Sprinter和grbl。
 * 版权所有 (c) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * 本程序是自由软件：您可以重新分发或修改它
 * 根据GNU通用公共许可证的条款，第3版或
 * (根据您的选择)任何后续版本。
 *
 * 本程序发布的目的是为了提供便利，
 * 但没有任何担保；甚至没有实质性的担保
 * 对适销性或适用性的保证。参见
 * GNU通用公共许可证以获取更多详细信息。
 *
 * 您应该收到一份GNU通用公共许可证的副本
 * 随同本程序一起。如果没有，请参阅<https://www.gnu.org/licenses/>。
 *
 */
#pragma once

/**
 * Changes.h
 *
 * 在编译时提醒有关配置更改。
 */

/**
 * 旧配置的警告
 */
#ifdef GITHUB_ACTION
  // 在CI测试期间跳过更改警告
#elif WATCH_TEMP_PERIOD > 500
  #error "WATCH_TEMP_PERIOD现在使用秒而不是毫秒。"
#elif DISABLED(THERMAL_PROTECTION_HOTENDS) && (defined(WATCH_TEMP_PERIOD) || defined(THERMAL_PROTECTION_PERIOD))
  #error "现在使用THERMAL_PROTECTION_HOTENDS启用热失控保护。"
#elif DISABLED(THERMAL_PROTECTION_BED) && defined(THERMAL_PROTECTION_BED_PERIOD)
  #error "现在使用THERMAL_PROTECTION_BED启用床的热失控保护。"
#elif defined(NO_FAN_SLOWING_IN_PID_TUNING)
  #error "NO_FAN_SLOWING_IN_PID_TUNING现在是TEMP_TUNING_MAINTAIN_FAN。"
#elif (CORE_IS_XZ || CORE_IS_YZ) && ENABLED(Z_LATE_ENABLE)
  #error "Z_LATE_ENABLE不能与COREXZ、COREZX、COREYZ或COREZY一起使用。"
#elif defined(X_HOME_RETRACT_MM)
  #error "[XYZ]_HOME_RETRACT_MM设置已更名为[XYZ]_HOME_BUMP_MM。"
#elif defined(SDCARDDETECTINVERTED)
  #error "SDCARDDETECTINVERTED现在是SD_DETECT_STATE（HIGH）。"
#elif defined(SD_DETECT_INVERTED)
  #error "SD_DETECT_INVERTED现在是SD_DETECT_STATE（HIGH）。"
#elif defined(BTENABLED)
  #error "BTENABLED现在是BLUETOOTH。"
#elif defined(CUSTOM_MENDEL_NAME)
  #error "CUSTOM_MENDEL_NAME现在是CUSTOM_MACHINE_NAME。"
#elif defined(HAS_AUTOMATIC_VERSIONING)
  #error "HAS_AUTOMATIC_VERSIONING现在是CUSTOM_VERSION_FILE。"
#elif defined(USE_AUTOMATIC_VERSIONING)
  #error "USE_AUTOMATIC_VERSIONING现在是CUSTOM_VERSION_FILE。"
#elif defined(SDSLOW)
  #error "SDSLOW已弃用。请将SD_SPI_SPEED设置为SPI_HALF_SPEED。"
#elif defined(SDEXTRASLOW)
  #error "SDEXTRASLOW已弃用。请将SD_SPI_SPEED设置为SPI_QUARTER_SPEED。"
#elif defined(FILAMENT_SENSOR)
  #error "FILAMENT_SENSOR现在是FILAMENT_WIDTH_SENSOR。"
#elif defined(ENDSTOPPULLUP_FIL_RUNOUT)
  #error "ENDSTOPPULLUP_FIL_RUNOUT现在是FIL_RUNOUT_PULLUP。"
#elif defined(DISABLE_MAX_ENDSTOPS) || defined(DISABLE_MIN_ENDSTOPS)
  #error "DISABLE_MAX_ENDSTOPS和DISABLE_MIN_ENDSTOPS已弃用。端点将自动确定。"
#elif defined(LANGUAGE_INCLUDE)
  #error "LANGUAGE_INCLUDE已被LCD_LANGUAGE取代。"
#elif defined(EXTRUDER_OFFSET_X) || defined(EXTRUDER_OFFSET_Y)
  #error "EXTRUDER_OFFSET_[XY]已弃用。请改用HOTEND_OFFSET_[XY]。"
#elif defined(PID_PARAMS_PER_EXTRUDER)
  #error "PID_PARAMS_PER_EXTRUDER已弃用。请改用PID_PARAMS_PER_HOTEND。"
#elif defined(EXTRUDER_WATTS) || defined(BED_WATTS)
  #error "EXTRUDER_WATTS和BED_WATTS已弃用，请删除。"
#elif defined(SERVO_ENDSTOP_ANGLES)
  #error "SERVO_ENDSTOP_ANGLES已弃用。请改用Z_SERVO_ANGLES。"
#elif defined(X_ENDSTOP_SERVO_NR) || defined(Y_ENDSTOP_SERVO_NR)
  #error "X_ENDSTOP_SERVO_NR和Y_ENDSTOP_SERVO_NR已弃用，请删除。"
#elif defined(Z_ENDSTOP_SERVO_NR)
  #error "Z_ENDSTOP_SERVO_NR现在是Z_PROBE_SERVO_NR。"
#elif defined(DEFAULT_XYJERK)
  #error "DEFAULT_XYJERK已弃用。请改用DEFAULT_XJERK和DEFAULT_YJERK。"
#elif defined(XY_TRAVEL_SPEED)
  #error "XY_TRAVEL_SPEED现在是XY_PROBE_FEEDRATE。"
#elif defined(XY_PROBE_SPEED)
  #error "XY_PROBE_SPEED现在是XY_PROBE_FEEDRATE。"
#elif defined(Z_PROBE_SPEED_FAST)
  #error "Z_PROBE_SPEED_FAST现在是Z_PROBE_FEEDRATE_FAST。"
#elif defined(Z_PROBE_SPEED_SLOW)
  #error "Z_PROBE_SPEED_SLOW现在是Z_PROBE_FEEDRATE_SLOW。"
#elif defined(PROBE_SERVO_DEACTIVATION_DELAY)
  #error "PROBE_SERVO_DEACTIVATION_DELAY已弃用。请改用DEACTIVATE_SERVOS_AFTER_MOVE。"
#elif defined(SERVO_DEACTIVATION_DELAY)
  #error "SERVO_DEACTIVATION_DELAY现在是SERVO_DELAY。"
#elif ENABLED(FILAMENTCHANGEENABLE)
  #error "FILAMENTCHANGEENABLE现在是ADVANCED_PAUSE_FEATURE。"
#elif ENABLED(FILAMENT_CHANGE_FEATURE)
  #error "FILAMENT_CHANGE_FEATURE现在是ADVANCED_PAUSE_FEATURE。"
#elif defined(FILAMENT_CHANGE_X_POS) || defined(FILAMENT_CHANGE_Y_POS)
  #error "FILAMENT_CHANGE_[XY]_POS现在使用NOZZLE_PARK_POINT设置。"
#elif defined(FILAMENT_CHANGE_Z_ADD)
  #error "FILAMENT_CHANGE_Z_ADD现在使用NOZZLE_PARK_POINT设置。"
#elif defined(FILAMENT_CHANGE_XY_FEEDRATE)
  #error "FILAMENT_CHANGE_XY_FEEDRATE现在是NOZZLE_PARK_XY_FEEDRATE。"
#elif defined(FILAMENT_CHANGE_Z_FEEDRATE)
  #error "FILAMENT_CHANGE_Z_FEEDRATE现在是NOZZLE_PARK_Z_FEEDRATE。"
#elif defined(PAUSE_PARK_X_POS) || defined(PAUSE_PARK_Y_POS)
  #error "PAUSE_PARK_[XY]_POS is now set with NOZZLE_PARK_POINT."
#elif defined(PAUSE_PARK_Z_ADD)
  #error "PAUSE_PARK_Z_ADD现在使用NOZZLE_PARK_POINT进行设置。"
#elif defined(PAUSE_PARK_XY_FEEDRATE)
  #error "PAUSE_PARK_XY_FEEDRATE现在使用NOZZLE_PARK_XY_FEEDRATE进行设置。"
#elif defined(PAUSE_PARK_Z_FEEDRATE)
  #error "PAUSE_PARK_Z_FEEDRATE现在使用NOZZLE_PARK_Z_FEEDRATE进行设置。"
#elif defined(FILAMENT_CHANGE_RETRACT_FEEDRATE)
  #error "FILAMENT_CHANGE_RETRACT_FEEDRATE现在使用PAUSE_PARK_RETRACT_FEEDRATE进行设置。"
#elif defined(FILAMENT_CHANGE_RETRACT_LENGTH)
  #error "FILAMENT_CHANGE_RETRACT_LENGTH现在使用PAUSE_PARK_RETRACT_LENGTH进行设置。"
#elif defined(FILAMENT_CHANGE_EXTRUDE_FEEDRATE)
  #error "FILAMENT_CHANGE_EXTRUDE_FEEDRATE现在使用ADVANCED_PAUSE_PURGE_FEEDRATE进行设置。"
#elif defined(ADVANCED_PAUSE_EXTRUDE_FEEDRATE)
  #error "ADVANCED_PAUSE_EXTRUDE_FEEDRATE现在使用ADVANCED_PAUSE_PURGE_FEEDRATE进行设置。"
#elif defined(FILAMENT_CHANGE_EXTRUDE_LENGTH)
  #error "FILAMENT_CHANGE_EXTRUDE_LENGTH现在使用ADVANCED_PAUSE_PURGE_LENGTH进行设置。"
#elif defined(ADVANCED_PAUSE_EXTRUDE_LENGTH)
  #error "ADVANCED_PAUSE_EXTRUDE_LENGTH现在使用ADVANCED_PAUSE_PURGE_LENGTH进行设置。"
#elif defined(FILAMENT_CHANGE_NOZZLE_TIMEOUT)
  #error "FILAMENT_CHANGE_NOZZLE_TIMEOUT现在使用PAUSE_PARK_NOZZLE_TIMEOUT进行设置。"
#elif defined(FILAMENT_CHANGE_NUMBER_OF_ALERT_BEEPS)
  #error "FILAMENT_CHANGE_NUMBER_OF_ALERT_BEEPS现在使用FILAMENT_CHANGE_ALERT_BEEPS进行设置。"
#elif defined(FILAMENT_CHANGE_NO_STEPPER_TIMEOUT)
  #error "FILAMENT_CHANGE_NO_STEPPER_TIMEOUT现在使用PAUSE_PARK_NO_STEPPER_TIMEOUT进行设置。"
#elif defined(PLA_PREHEAT_HOTEND_TEMP)
  #error "PLA_PREHEAT_HOTEND_TEMP现在使用PREHEAT_1_TEMP_HOTEND进行设置。"
#elif defined(PLA_PREHEAT_HPB_TEMP)
  #error "PLA_PREHEAT_HPB_TEMP现在使用PREHEAT_1_TEMP_BED进行设置。"
#elif defined(PLA_PREHEAT_FAN_SPEED)
  #error "PLA_PREHEAT_FAN_SPEED现在使用PREHEAT_1_FAN_SPEED进行设置。"
#elif defined(ABS_PREHEAT_HOTEND_TEMP)
  #error "ABS_PREHEAT_HOTEND_TEMP现在使用PREHEAT_2_TEMP_HOTEND进行设置。"
#elif defined(ABS_PREHEAT_HPB_TEMP)
  #error "ABS_PREHEAT_HPB_TEMP现在使用PREHEAT_2_TEMP_BED进行设置。"
#elif defined(ABS_PREHEAT_FAN_SPEED)
  #error "ABS_PREHEAT_FAN_SPEED现在使用PREHEAT_2_FAN_SPEED进行设置。"
#elif defined(ENDSTOPS_ONLY_FOR_HOMING)
  #error "ENDSTOPS_ONLY_FOR_HOMING已弃用。请改用（禁用）ENDSTOPS_ALWAYS_ON_DEFAULT。"
#elif defined(HOMING_FEEDRATE)
  #error "HOMING_FEEDRATE现在使用HOMING_FEEDRATE_MM_M数组进行设置。"
#elif (defined(HOMING_FEEDRATE_XY) || defined(HOMING_FEEDRATE_Z)) && !defined(HOMING_FEEDRATE_MM_M)
  #error "HOMING_FEEDRATE_XY和HOMING_FEEDRATE_Z现在使用HOMING_FEEDRATE_MM_M数组进行设置。"
#elif defined(MANUAL_HOME_POSITIONS)
  #error "MANUAL_HOME_POSITIONS已弃用。请根据需要设置MANUAL_[XYZ]_HOME_POS。"
#elif defined(PID_ADD_EXTRUSION_RATE)
  #error "PID_ADD_EXTRUSION_RATE现在称为PID_EXTRUSION_SCALING，并且默认处于禁用状态。"
#elif defined(Z_RAISE_BEFORE_HOMING)
  #error "Z_RAISE_BEFORE_HOMING现在称为Z_CLEARANCE_FOR_HOMING。"
#elif defined(MIN_Z_HEIGHT_FOR_HOMING)
  #error "MIN_Z_HEIGHT_FOR_HOMING现在称为Z_CLEARANCE_FOR_HOMING。"
#elif defined(Z_HOMING_HEIGHT)
  #error "Z_HOMING_HEIGHT现在称为Z_CLEARANCE_FOR_HOMING。"
#elif defined(Z_RAISE_BEFORE_PROBING) || defined(Z_RAISE_AFTER_PROBING)
  #error "Z_RAISE_(BEFORE|AFTER)_PROBING已弃用。请改用Z_CLEARANCE_DEPLOY_PROBE和Z_AFTER_PROBING。"
#elif defined(Z_RAISE_PROBE_DEPLOY_STOW) || defined(Z_RAISE_BETWEEN_PROBINGS)
  #error "Z_RAISE_PROBE_DEPLOY_STOW和Z_RAISE_BETWEEN_PROBINGS现在称为Z_CLEARANCE_DEPLOY_PROBE和Z_CLEARANCE_BETWEEN_PROBES。"
#elif defined(Z_PROBE_DEPLOY_HEIGHT) || defined(Z_PROBE_TRAVEL_HEIGHT)
  #error "Z_PROBE_DEPLOY_HEIGHT和Z_PROBE_TRAVEL_HEIGHT现在称为Z_CLEARANCE_DEPLOY_PROBE和Z_CLEARANCE_BETWEEN_PROBES。"
#elif defined(MANUAL_BED_LEVELING)
  #error "MANUAL_BED_LEVELING现在称为LCD_BED_LEVELING。"
#elif defined(MESH_HOME_SEARCH_Z)
  #error "MESH_HOME_SEARCH_Z现在称为LCD_PROBE_Z_RANGE。"
#elif defined(MANUAL_PROBE_Z_RANGE)
  #error "MANUAL_PROBE_Z_RANGE现在称为LCD_PROBE_Z_RANGE。"
#elif !defined(MIN_STEPS_PER_SEGMENT)
  #error "请将'const int dropsegments'替换为'#define MIN_STEPS_PER_SEGMENT'（并增加1）。"
#elif MIN_STEPS_PER_SEGMENT <= 0
  #error "MIN_STEPS_PER_SEGMENT必须至少为1。"
#elif defined(PREVENT_DANGEROUS_EXTRUDE)
  #error "PREVENT_DANGEROUS_EXTRUDE现在称为PREVENT_COLD_EXTRUSION。"
#elif defined(SCARA)
  #error "SCARA现在称为MORGAN_SCARA。"
#elif defined(ENABLE_AUTO_BED_LEVELING)
  #error "ENABLE_AUTO_BED_LEVELING已弃用。请指定AUTO_BED_LEVELING_LINEAR、AUTO_BED_LEVELING_BILINEAR或AUTO_BED_LEVELING_3POINT。"
#elif defined(AUTO_BED_LEVELING_FEATURE)
#error "AUTO_BED_LEVELING_FEATURE已弃用。请指定AUTO_BED_LEVELING_LINEAR、AUTO_BED_LEVELING_BILINEAR或AUTO_BED_LEVELING_3POINT。"
#elif defined(ABL_GRID_POINTS)
  #error "ABL_GRID_POINTS现在称为GRID_MAX_POINTS_X和GRID_MAX_POINTS_Y。"
#elif defined(ABL_GRID_POINTS_X) || defined(ABL_GRID_POINTS_Y)
  #error "ABL_GRID_POINTS_[XY]现在称为GRID_MAX_POINTS_[XY]。"
#elif defined(ABL_GRID_MAX_POINTS_X) || defined(ABL_GRID_MAX_POINTS_Y)
  #error "ABL_GRID_MAX_POINTS_[XY]现在称为GRID_MAX_POINTS_[XY]。"
#elif defined(MESH_NUM_X_POINTS) || defined(MESH_NUM_Y_POINTS)
  #error "MESH_NUM_[XY]_POINTS现在称为GRID_MAX_POINTS_[XY]。"
#elif defined(UBL_MESH_NUM_X_POINTS) || defined(UBL_MESH_NUM_Y_POINTS)
  #error "UBL_MESH_NUM_[XY]_POINTS现在称为GRID_MAX_POINTS_[XY]。"
#elif defined(UBL_G26_MESH_VALIDATION)
  #error "UBL_G26_MESH_VALIDATION现在称为G26_MESH_VALIDATION。"
#elif defined(UBL_MESH_EDIT_ENABLED)
  #error "UBL_MESH_EDIT_ENABLED现在称为G26_MESH_VALIDATION。"
#elif defined(UBL_MESH_EDITING)
  #error "UBL_MESH_EDITING现在称为G26_MESH_VALIDATION。"
#elif defined(BLTOUCH_HEATERS_OFF)
  #error "BLTOUCH_HEATERS_OFF现在称为PROBING_HEATERS_OFF。"
#elif defined(BLTOUCH_V3)
  #error "BLTOUCH_V3已过时。"
#elif defined(BLTOUCH_FORCE_OPEN_DRAIN_MODE)
  #error "BLTOUCH_FORCE_OPEN_DRAIN_MODE已过时。"
#elif defined(BEEPER)
  #error "BEEPER现在称为BEEPER_PIN。"
#elif defined(SDCARDDETECT)
  #error "SDCARDDETECT现在称为SD_DETECT_PIN。"
#elif defined(STAT_LED_RED) || defined(STAT_LED_BLUE)
  #error "STAT_LED_RED/STAT_LED_BLUE现在称为STAT_LED_RED_PIN/STAT_LED_BLUE_PIN。"
#elif defined(LCD_PIN_BL)
  #error "LCD_PIN_BL现在称为LCD_BACKLIGHT_PIN。"
#elif defined(LCD_PIN_RESET)
  #error "LCD_PIN_RESET现在称为LCD_RESET_PIN。"
#elif defined(EXTRUDER_0_AUTO_FAN_PIN) || defined(EXTRUDER_1_AUTO_FAN_PIN) || defined(EXTRUDER_2_AUTO_FAN_PIN) || defined(EXTRUDER_3_AUTO_FAN_PIN)
  #error "EXTRUDER_[0123]_AUTO_FAN_PIN现在称为E[0123]_AUTO_FAN_PIN。"
#elif defined(min_software_endstops) || defined(max_software_endstops)
  #error "(min|max)_software_endstops现在称为(MIN|MAX)_SOFTWARE_ENDSTOPS。"
#elif ENABLED(Z_PROBE_SLED) && defined(SLED_PIN)
  #error "请使用SOL1_PIN替换SLED_PIN（适用于Z_PROBE_SLED和SOLENOID_PROBE）。"
#elif defined(CONTROLLERFAN_PIN)
  #error "CONTROLLERFAN_PIN现在称为CONTROLLER_FAN_PIN，通过USE_CONTROLLER_FAN启用。"
#elif defined(CONTROLLERFAN_SPEED)
  #error "CONTROLLERFAN_SPEED现在称为CONTROLLERFAN_SPEED_ACTIVE。"
#elif defined(CONTROLLERFAN_SECS)
  #error "CONTROLLERFAN_SECS现在称为CONTROLLERFAN_IDLE_TIME。"
#elif defined(MIN_RETRACT)
  #error "MIN_RETRACT现在称为MIN_AUTORETRACT和MAX_AUTORETRACT。"
#elif defined(ADVANCE)
  #error "ADVANCE现在称为LIN_ADVANCE。"
#elif defined(LIN_ADVANCE_E_D_RATIO)
  #error "LIN_ADVANCE（1.5）不再使用LIN_ADVANCE_E_D_RATIO。"
#elif defined(NEOPIXEL_RGBW_LED)
  #error "NEOPIXEL_RGBW_LED现在称为NEOPIXEL_LED。"
#elif ENABLED(DELTA) && defined(DELTA_PROBEABLE_RADIUS)
  #error "删除DELTA_PROBEABLE_RADIUS，改用PROBING_MARGIN来插入探针区域。"
#elif ENABLED(DELTA) && defined(DELTA_CALIBRATION_RADIUS)
  #error "删除DELTA_CALIBRATION_RADIUS，改用PROBING_MARGIN来插入探针区域。"
#elif defined(UBL_MESH_INSET)
  #error "UBL_MESH_INSET现在只称为MESH_INSET。"
#elif defined(UBL_MESH_MIN_X) || defined(UBL_MESH_MIN_Y) || defined(UBL_MESH_MAX_X) || defined(UBL_MESH_MAX_Y)
  #error "UBL_MESH_(MIN|MAX)_[XY]现在只称为MESH_(MIN|MAX)_[XY]。"
#elif defined(ABL_PROBE_PT_1_X) || defined(ABL_PROBE_PT_1_Y) || defined(ABL_PROBE_PT_2_X) || defined(ABL_PROBE_PT_2_Y) || defined(ABL_PROBE_PT_3_X) || defined(ABL_PROBE_PT_3_Y)
  #error "不再需要ABL_PROBE_PT_[123]_[XY]。请将其删除。"
#elif defined(UBL_PROBE_PT_1_X) || defined(UBL_PROBE_PT_1_Y) || defined(UBL_PROBE_PT_2_X) || defined(UBL_PROBE_PT_2_Y) || defined(UBL_PROBE_PT_3_X) || defined(UBL_PROBE_PT_3_Y)
  #error "不再需要UBL_PROBE_PT_[123]_[XY]。请将其删除。"
#elif defined(MIN_PROBE_EDGE)
  #error "MIN_PROBE_EDGE现在称为PROBING_MARGIN。"
#elif defined(MIN_PROBE_EDGE_LEFT)
  #error "MIN_PROBE_EDGE_LEFT现在称为PROBING_MARGIN_LEFT。"
#elif defined(MIN_PROBE_EDGE_RIGHT)
  #error "MIN_PROBE_EDGE_RIGHT现在称为PROBING_MARGIN_RIGHT。"
#elif defined(MIN_PROBE_EDGE_FRONT)
  #error "MIN_PROBE_EDGE_FRONT现在称为PROBING_MARGIN_FRONT。"
#elif defined(MIN_PROBE_EDGE_BACK)
  #error "MIN_PROBE_EDGE_BACK现在称为PROBING_MARGIN_BACK。"
#elif defined(LEFT_PROBE_BED_POSITION)
  #error "LEFT_PROBE_BED_POSITION已过时。请使用PROBING_MARGIN或PROBING_MARGIN_LEFT设置边距。"
#elif defined(RIGHT_PROBE_BED_POSITION)
  #error "RIGHT_PROBE_BED_POSITION已过时。请使用PROBING_MARGIN或PROBING_MARGIN_RIGHT设置边距。"
#elif defined(FRONT_PROBE_BED_POSITION)
#error "FRONT_PROBE_BED_POSITION已过时。请使用PROBING_MARGIN或PROBING_MARGIN_FRONT设置边距。"
#elif defined(BACK_PROBE_BED_POSITION)
  #error "BACK_PROBE_BED_POSITION已过时。请使用PROBING_MARGIN或PROBING_MARGIN_BACK设置边距。"
#elif defined(ENABLE_MESH_EDIT_GFX_OVERLAY)
  #error "ENABLE_MESH_EDIT_GFX_OVERLAY现在称为MESH_EDIT_GFX_OVERLAY。"
#elif defined(BABYSTEP_ZPROBE_GFX_REVERSE)
  #error "BABYSTEP_ZPROBE_GFX_REVERSE现在由OVERLAY_GFX_REVERSE设置。"
#elif defined(UBL_GRANULAR_SEGMENTATION_FOR_CARTESIAN)
  #error "UBL_GRANULAR_SEGMENTATION_FOR_CARTESIAN现在称为SEGMENT_LEVELED_MOVES。"
#elif HAS_PID_HEATING && (defined(K1) || !defined(PID_K1))
  #error "K1现在称为PID_K1。"
#elif defined(PROBE_DOUBLE_TOUCH)
  #error "PROBE_DOUBLE_TOUCH现在称为MULTIPLE_PROBING。"
#elif defined(ANET_KEYPAD_LCD)
  #error "ANET_KEYPAD_LCD现在称为ZONESTAR_LCD。"
#elif defined(LCD_I2C_SAINSMART_YWROBOT)
  #error "LCD_I2C_SAINSMART_YWROBOT现在称为LCD_SAINSMART_I2C_(1602|2004)。"
#elif defined(MEASURED_LOWER_LIMIT) || defined(MEASURED_UPPER_LIMIT)
  #error "MEASURED_(UPPER|LOWER)_LIMIT现在称为FILWIDTH_ERROR_MARGIN。"
#elif defined(HAVE_TMCDRIVER)
  #error "HAVE_TMCDRIVER现在是[AXIS]_DRIVER_TYPE TMC26X。"
#elif defined(STEALTHCHOP)
  #error "STEALTHCHOP现在是STEALTHCHOP_(XY|Z|E)。"
#elif defined(HAVE_TMC26X)
  #error "HAVE_TMC26X现在是[AXIS]_DRIVER_TYPE TMC26X。"
#elif defined(HAVE_TMC2130)
  #error "HAVE_TMC2130现在是[AXIS]_DRIVER_TYPE TMC2130。"
#elif defined(HAVE_TMC2208)
  #error "HAVE_TMC2208现在是[AXIS]_DRIVER_TYPE TMC2208。"
#elif defined(HAVE_L6470DRIVER)
  #error "HAVE_L6470DRIVER已过时。Marlin不再支持L64xx步进电机驱动器。"
#elif defined(X_IS_TMC) || defined(X2_IS_TMC) || defined(Y_IS_TMC) || defined(Y2_IS_TMC) || defined(Z_IS_TMC) || defined(Z2_IS_TMC) || defined(Z3_IS_TMC) \
   || defined(E0_IS_TMC) || defined(E1_IS_TMC) || defined(E2_IS_TMC) || defined(E3_IS_TMC) || defined(E4_IS_TMC) || defined(E5_IS_TMC) || defined(E6_IS_TMC) || defined(E7_IS_TMC)
  #error "[AXIS]_IS_TMC现在是[AXIS]_DRIVER_TYPE TMC26X。"
#elif defined(X_IS_TMC26X) || defined(X2_IS_TMC26X) || defined(Y_IS_TMC26X) || defined(Y2_IS_TMC26X) || defined(Z_IS_TMC26X) || defined(Z2_IS_TMC26X) || defined(Z3_IS_TMC26X) \
   || defined(E0_IS_TMC26X) || defined(E1_IS_TMC26X) || defined(E2_IS_TMC26X) || defined(E3_IS_TMC26X) || defined(E4_IS_TMC26X) || defined(E5_IS_TMC26X) || defined(E6_IS_TMC26X) || defined(E7_IS_TMC26X)
  #error "[AXIS]_IS_TMC26X现在是[AXIS]_DRIVER_TYPE TMC26X。"
#elif defined(X_IS_TMC2130) || defined(X2_IS_TMC2130) || defined(Y_IS_TMC2130) || defined(Y2_IS_TMC2130) || defined(Z_IS_TMC2130) || defined(Z2_IS_TMC2130) || defined(Z3_IS_TMC2130) \
   || defined(E0_IS_TMC2130) || defined(E1_IS_TMC2130) || defined(E2_IS_TMC2130) || defined(E3_IS_TMC2130) || defined(E4_IS_TMC2130) || defined(E5_IS_TMC2130) || defined(E6_IS_TMC2130) || defined(E7_IS_TMC2130)
  #error "[AXIS]_IS_TMC2130现在是[AXIS]_DRIVER_TYPE TMC2130。"
#elif defined(X_IS_TMC2208) || defined(X2_IS_TMC2208) || defined(Y_IS_TMC2208) || defined(Y2_IS_TMC2208) || defined(Z_IS_TMC2208) || defined(Z2_IS_TMC2208) || defined(Z3_IS_TMC2208) \
   || defined(E0_IS_TMC2208) || defined(E1_IS_TMC2208) || defined(E2_IS_TMC2208) || defined(E3_IS_TMC2208) || defined(E4_IS_TMC2208) || defined(E5_IS_TMC2208) || defined(E6_IS_TMC2208) || defined(E7_IS_TMC2208)
  #error "[AXIS]_IS_TMC2208现在是[AXIS]_DRIVER_TYPE TMC2208。"
#elif defined(AUTOMATIC_CURRENT_CONTROL)
  #error "AUTOMATIC_CURRENT_CONTROL现在是MONITOR_DRIVER_STATUS。"
#elif defined(FILAMENT_CHANGE_LOAD_LENGTH)
  #error "FILAMENT_CHANGE_LOAD_LENGTH现在是FILAMENT_CHANGE_FAST_LOAD_LENGTH。"
#elif defined(LEVEL_CORNERS_INSET)
  #error "LEVEL_CORNERS_INSET现在是BED_TRAMMING_INSET_LFRB。"
#elif defined(BEZIER_JERK_CONTROL)
  #error "BEZIER_JERK_CONTROL现在是S_CURVE_ACCELERATION。"
#elif HAS_JUNCTION_DEVIATION && defined(JUNCTION_DEVIATION_FACTOR)
  #error "JUNCTION_DEVIATION_FACTOR现在是JUNCTION_DEVIATION_MM。"
#elif defined(JUNCTION_ACCELERATION_FACTOR)
  #error "JUNCTION_ACCELERATION_FACTOR已过时。请从Configuration_adv.h中删除它。"
#elif defined(JUNCTION_ACCELERATION)
  #error "JUNCTION_ACCELERATION已过时。请从Configuration_adv.h中删除它。"
#elif defined(MAX7219_DEBUG_STEPPER_HEAD)
  #error "MAX7219_DEBUG_STEPPER_HEAD现在是MAX7219_DEBUG_PLANNER_HEAD。"
#elif defined(MAX7219_DEBUG_STEPPER_TAIL)
  #error "MAX7219_DEBUG_STEPPER_TAIL现在是MAX7219_DEBUG_PLANNER_TAIL。"
#elif defined(MAX7219_DEBUG_STEPPER_QUEUE)
  #error "MAX7219_DEBUG_STEPPER_QUEUE现在是MAX7219_DEBUG_PLANNER_QUEUE。"
#elif defined(ENDSTOP_NOISE_FILTER)
  #error "ENDSTOP_NOISE_FILTER现在是ENDSTOP_NOISE_THRESHOLD [2-7]。"
#elif defined(RETRACT_ZLIFT)
  #error "RETRACT_ZLIFT现在是RETRACT_ZRAISE。"
#elif defined(TOOLCHANGE_FS_INIT_BEFORE_SWAP)
#error "TOOLCHANGE_FS_INIT_BEFORE_SWAP现在称为TOOLCHANGE_FS_SLOW_FIRST_PRIME。"
#elif defined(TOOLCHANGE_PARK_ZLIFT) || defined(TOOLCHANGE_UNPARK_ZLIFT)
  #error "TOOLCHANGE_PARK_ZLIFT和TOOLCHANGE_UNPARK_ZLIFT现在称为TOOLCHANGE_ZRAISE。"
#elif defined(SINGLENOZZLE_TOOLCHANGE_ZRAISE)
  #error "SINGLENOZZLE_TOOLCHANGE_ZRAISE现在称为TOOLCHANGE_ZRAISE。"
#elif defined(SINGLENOZZLE_SWAP_LENGTH)
  #error "SINGLENOZZLE_SWAP_LENGTH现在称为TOOLCHANGE_FIL_SWAP_LENGTH。"
#elif defined(SINGLENOZZLE_SWAP_RETRACT_SPEED)
  #error "SINGLENOZZLE_SWAP_RETRACT_SPEED现在称为TOOLCHANGE_FIL_SWAP_RETRACT_SPEED。"
#elif defined(SINGLENOZZLE_SWAP_PRIME_SPEED)
  #error "SINGLENOZZLE_SWAP_PRIME_SPEED现在称为TOOLCHANGE_FIL_SWAP_PRIME_SPEED。"
#elif defined(SINGLENOZZLE_SWAP_PARK)
  #error "SINGLENOZZLE_SWAP_PARK现在称为TOOLCHANGE_PARK。"
#elif defined(SINGLENOZZLE_TOOLCHANGE_XY)
  #error "SINGLENOZZLE_TOOLCHANGE_XY现在称为TOOLCHANGE_PARK_XY。"
#elif defined(SINGLENOZZLE_PARK_XY_FEEDRATE)
  #error "SINGLENOZZLE_PARK_XY_FEEDRATE现在称为TOOLCHANGE_PARK_XY_FEEDRATE。"
#elif defined(PARKING_EXTRUDER_SECURITY_RAISE)
  #error "PARKING_EXTRUDER_SECURITY_RAISE现在称为TOOLCHANGE_ZRAISE。"
#elif defined(SWITCHING_TOOLHEAD_SECURITY_RAISE)
  #error "SWITCHING_TOOLHEAD_SECURITY_RAISE现在称为TOOLCHANGE_ZRAISE。"
#elif defined(G0_FEEDRATE) && G0_FEEDRATE == 0
  #error "G0_FEEDRATE现在用于设置G0进给速度。"
#elif defined(MBL_Z_STEP)
  #error "MBL_Z_STEP现在称为MESH_EDIT_Z_STEP。"
#elif defined(CHDK)
  #error "CHDK现在称为CHDK_PIN。"
#elif ANY_PIN( \
        MAX6675_SS, MAX6675_SS2, MAX6675_SS3, MAX6675_CS, MAX6675_CS2, MAX6675_CS3,\
        MAX31855_SS, MAX31855_SS2, MAX31855_SS3, MAX31855_CS, MAX31855_CS2, MAX31855_CS3, \
        MAX31865_SS, MAX31865_SS2, MAX31865_SS3, MAX31865_CS, MAX31865_CS2, MAX31865_CS3)
  #warning "MAX*_SS_PIN、MAX*_SS2_PIN、MAX*_SS3_PIN、MAX*_CS_PIN、MAX*_CS2_PIN和MAX*_CS3_PIN已过时。请改用TEMP_0_CS_PIN/TEMP_1_CS_PIN/TEMP_2_CS_PIN。"
#elif ANY_PIN(MAX6675_SCK, MAX31855_SCK, MAX31865_SCK)
  #warning "MAX*_SCK_PIN已过时。请改用TEMP_0_SCK_PIN/TEMP_1_SCK_PIN/TEMP_2_SCK_PIN。"
#elif ANY_PIN(MAX6675_MISO, MAX6675_DO, MAX31855_MISO, MAX31855_DO, MAX31865_MISO, MAX31865_DO)
  #warning "MAX*_MISO_PIN和MAX*_DO_PIN已过时。请改用TEMP_0_MISO_PIN/TEMP_1_MISO_PIN/TEMP_2_MISO_PIN。"
#elif PIN_EXISTS(MAX31865_MOSI)
  #warning "MAX31865_MOSI_PIN已过时。请改用TEMP_0_MOSI_PIN/TEMP_1_MOSI_PIN/TEMP_2_MOSI_PIN。"
#elif ANY_PIN(THERMO_CS1_PIN, THERMO_CS2_PIN, THERMO_CS3_PIN, THERMO_DO_PIN, THERMO_SCK_PIN)
  #error "THERMO_*_PIN现在是TEMP_n_CS_PIN，TEMP_n_SCK_PIN，TEMP_n_MOSI_PIN，TEMP_n_MISO_PIN。"
#elif defined(MAX31865_SENSOR_OHMS)
  #error "MAX31865_SENSOR_OHMS现在是MAX31865_SENSOR_OHMS_0。"
#elif defined(MAX31865_CALIBRATION_OHMS)
  #error "MAX31865_CALIBRATION_OHMS现在是MAX31865_CALIBRATION_OHMS_0。"
#elif defined(SPINDLE_LASER_ENABLE)
  #error "SPINDLE_LASER_ENABLE现在是SPINDLE_FEATURE或LASER_FEATURE。"
#elif defined(SPINDLE_LASER_ENABLE_PIN)
  #error "SPINDLE_LASER_ENABLE_PIN现在是SPINDLE_LASER_ENA_PIN。"
#elif defined(SPINDLE_DIR_CHANGE)
  #error "SPINDLE_DIR_CHANGE现在是SPINDLE_CHANGE_DIR。"
#elif defined(SPINDLE_STOP_ON_DIR_CHANGE)
  #error "SPINDLE_STOP_ON_DIR_CHANGE现在是SPINDLE_CHANGE_DIR_STOP。"
#elif defined(SPINDLE_LASER_ACTIVE_HIGH)
  #error "SPINDLE_LASER_ACTIVE_HIGH现在是SPINDLE_LASER_ACTIVE_STATE。"
#elif defined(SPINDLE_LASER_ENABLE_INVERT)
  #error "SPINDLE_LASER_ENABLE_INVERT现在是SPINDLE_LASER_ACTIVE_STATE。"
#elif defined(LASER_POWER_INLINE)
  #error "LASER_POWER_INLINE不再需要，在' M3 I'启用内联模式，' M5 I'禁用内联模式。"
#elif defined(LASER_POWER_INLINE_TRAPEZOID)
  #error "LASER_POWER_INLINE_TRAPEZOID现在是LASER_POWER_TRAP。"
#elif defined(LASER_POWER_INLINE_TRAPEZOID_CONT)
  #error "LASER_POWER_INLINE_TRAPEZOID_CONT现在是LASER_POWER_TRAP。"
#elif defined(LASER_POWER_INLINE_TRAPEZOID_PER)
  #error "LASER_POWER_INLINE_TRAPEZOID_CONT_PER现在是LASER_POWER_TRAP。"
#elif defined(LASER_POWER_INLINE_CONTINUOUS)
  #error "LASER_POWER_INLINE_CONTINUOUS不再需要，在' M3 I'启用内联模式，' M5 I'禁用内联模式。"
#elif defined(CUTTER_POWER_DISPLAY)
  #error "CUTTER_POWER_DISPLAY现在称为CUTTER_POWER_UNIT。"
#elif defined(CHAMBER_HEATER_PIN)
  #error "CHAMBER_HEATER_PIN现在称为HEATER_CHAMBER_PIN。"
#elif defined(TMC_Z_CALIBRATION)
  #error "TMC_Z_CALIBRATION已弃用，改用MECHANICAL_GANTRY_CALIBRATION。"
#elif defined(Z_MIN_PROBE_ENDSTOP)
  #error "Z_MIN_PROBE_ENDSTOP不再需要。请将其删除。"
#elif defined(DUAL_NOZZLE_DUPLICATION_MODE)
  #error "DUAL_NOZZLE_DUPLICATION_MODE现在称为MULTI_NOZZLE_DUPLICATION。"
#elif defined(MENU_ITEM_CASE_LIGHT)
  #error "MENU_ITEM_CASE_LIGHT现在称为CASE_LIGHT_MENU。"
#elif defined(CASE_LIGHT_NEOPIXEL_COLOR)
  #error "CASE_LIGHT_NEOPIXEL_COLOR现在称为CASE_LIGHT_DEFAULT_COLOR。"
#elif defined(ABORT_ON_ENDSTOP_HIT_FEATURE_ENABLED)
#error "ABORT_ON_ENDSTOP_HIT_FEATURE_ENABLED现在称为SD_ABORT_ON_ENDSTOP_HIT。"
#elif defined(LPC_SD_LCD) || defined(LPC_SD_ONBOARD) || defined(LPC_SD_CUSTOM_CABLE)
  #error "LPC_SD_(LCD|ONBOARD|CUSTOM_CABLE)现在称为SDCARD_CONNECTION。"
#elif defined(USB_SD_DISABLED)
  #error "USB_SD_DISABLED现在称为NO_SD_HOST_DRIVE。"
#elif defined(USB_SD_ONBOARD)
  #error "USB_SD_ONBOARD已过时。请禁用NO_SD_HOST_DRIVE。"
#elif defined(PSU_ACTIVE_HIGH)
  #error "PSU_ACTIVE_HIGH现在称为PSU_ACTIVE_STATE。"
#elif POWER_SUPPLY == 1
  #error "将POWER_SUPPLY 1替换为启用PSU_CONTROL并将PSU_ACTIVE_STATE设置为'LOW'。"
#elif POWER_SUPPLY == 2
  #error "将POWER_SUPPLY 2替换为启用PSU_CONTROL并将PSU_ACTIVE_STATE设置为'HIGH'。"
#elif defined(POWER_SUPPLY)
  #error "POWER_SUPPLY现在已过时。请将其删除。"
#elif defined(MKS_ROBIN_TFT)
  #error "MKS_ROBIN_TFT现在称为FSMC_GRAPHICAL_TFT。"
#elif defined(SDPOWER)
  #error "SDPOWER现在称为SDPOWER_PIN。"
#elif defined(STRING_SPLASH_LINE1) || defined(STRING_SPLASH_LINE2)
  #error "STRING_SPLASH_LINE[12]现在已过时。请将其删除。"
#elif defined(Z_PROBE_ALLEN_KEY_DEPLOY_1_X) || defined(Z_PROBE_ALLEN_KEY_STOW_1_X)
  #error "Z_PROBE_ALLEN_KEY_(DEPLOY|STOW)坐标现在是单个设置。"
#elif defined(X_PROBE_OFFSET_FROM_EXTRUDER) || defined(Y_PROBE_OFFSET_FROM_EXTRUDER) || defined(Z_PROBE_OFFSET_FROM_EXTRUDER)
  #error "[XYZ]_PROBE_OFFSET_FROM_EXTRUDER现在是NOZZLE_TO_PROBE_OFFSET。"
#elif defined(MIN_PROBE_X) || defined(MIN_PROBE_Y) || defined(MAX_PROBE_X) || defined(MAX_PROBE_Y)
  #error "(MIN|MAX)_PROBE_[XY]现在在运行时计算。请将其删除。"
#elif defined(Z_STEPPER_ALIGN_X) || defined(Z_STEPPER_ALIGN_X)
  #error "Z_STEPPER_ALIGN_X和Z_STEPPER_ALIGN_Y现在合并为Z_STEPPER_ALIGN_XY。"
#elif defined(JUNCTION_DEVIATION)
  #error "JUNCTION_DEVIATION不再需要。请删除它。（参见CLASSIC_JERK）"
#elif defined(BABYSTEP_MULTIPLICATOR)
  #error "BABYSTEP_MULTIPLICATOR现在是BABYSTEP_MULTIPLICATOR_[XY|Z]。"
#elif defined(LULZBOT_TOUCH_UI)
  #error "LULZBOT_TOUCH_UI现在是TOUCH_UI_FTDI_EVE。"
#elif defined(PS_DEFAULT_OFF)
  #error "PS_DEFAULT_OFF现在是PSU_DEFAULT_OFF。"
#elif defined(FILAMENT_UNLOAD_RETRACT_LENGTH)
  #error "FILAMENT_UNLOAD_RETRACT_LENGTH现在是FILAMENT_UNLOAD_PURGE_RETRACT。"
#elif defined(FILAMENT_UNLOAD_DELAY)
  #error "FILAMENT_UNLOAD_DELAY现在是FILAMENT_UNLOAD_PURGE_DELAY。"
#elif defined(HOME_USING_SPREADCYCLE)
  #error "HOME_USING_SPREADCYCLE现在已过时。请删除它。"
#elif defined(DGUS_LCD)
  #error "DGUS_LCD现在是DGUS_LCD_UI (ORIGIN|FYSETC|HIPRECY)。"
#elif defined(DGUS_SERIAL_PORT)
  #error "DGUS_SERIAL_PORT现在是LCD_SERIAL_PORT。"
#elif defined(DGUS_BAUDRATE)
  #error "DGUS_BAUDRATE现在是LCD_BAUDRATE。"
#elif defined(DGUS_STATS_RX_BUFFER_OVERRUNS)
  #error "DGUS_STATS_RX_BUFFER_OVERRUNS现在是STATS_RX_BUFFER_OVERRUNS。"
#elif defined(ANYCUBIC_LCD_SERIAL_PORT)
  #error "ANYCUBIC_LCD_SERIAL_PORT现在是LCD_SERIAL_PORT。"
#elif defined(INTERNAL_SERIAL_PORT)
  #error "INTERNAL_SERIAL_PORT现在是MMU2_SERIAL_PORT。"
#elif defined(X_DUAL_ENDSTOPS_ADJUSTMENT) || defined(Y_DUAL_ENDSTOPS_ADJUSTMENT) || defined(Z_DUAL_ENDSTOPS_ADJUSTMENT)
  #error "[XYZ]_DUAL_ENDSTOPS_ADJUSTMENT现在是[XYZ]2_ENDSTOP_ADJUSTMENT。"
#elif defined(Z_TRIPLE_ENDSTOPS_ADJUSTMENT2) || defined(Z_TRIPLE_ENDSTOPS_ADJUSTMENT3)
  #error "Z_TRIPLE_ENDSTOPS_ADJUSTMENT[23]现在是Z[23]_ENDSTOP_ADJUSTMENT。"
#elif defined(Z_QUAD_ENDSTOPS_ADJUSTMENT2) || defined(Z_QUAD_ENDSTOPS_ADJUSTMENT3) || defined(Z_QUAD_ENDSTOPS_ADJUSTMENT4)
  #error "Z_QUAD_ENDSTOPS_ADJUSTMENT[234]现在是Z[234]_ENDSTOP_ADJUSTMENT。"
#elif defined(Z_DUAL_STEPPER_DRIVERS)
  #error "Z_DUAL_STEPPER_DRIVERS不再需要，请将其删除。"
#elif defined(Z_TRIPLE_STEPPER_DRIVERS)
  #error "Z_TRIPLE_STEPPER_DRIVERS不再需要，请将其删除。"
#elif defined(Z_QUAD_STEPPER_DRIVERS)
  #error "Z_QUAD_STEPPER_DRIVERS不再需要，请将其删除。"
#elif defined(Z_DUAL_ENDSTOPS) || defined(Z_TRIPLE_ENDSTOPS) || defined(Z_QUAD_ENDSTOPS)
  #error "Z_(DUAL|TRIPLE|QUAD)_ENDSTOPS现在是Z_MULTI_ENDSTOPS。"
#elif defined(DUGS_UI_MOVE_DIS_OPTION)
  #error "DUGS_UI_MOVE_DIS_OPTION的正确拼写是DGUS_UI_MOVE_DIS_OPTION。"
#elif defined(ORIG_E0_AUTO_FAN_PIN) || defined(ORIG_E1_AUTO_FAN_PIN) || defined(ORIG_E2_AUTO_FAN_PIN) || defined(ORIG_E3_AUTO_FAN_PIN) || defined(ORIG_E4_AUTO_FAN_PIN) || defined(ORIG_E5_AUTO_FAN_PIN) || defined(ORIG_E6_AUTO_FAN_PIN) || defined(ORIG_E7_AUTO_FAN_PIN)
  #error "ORIG_Ex_AUTO_FAN_PIN现在只需Ex_AUTO_FAN_PIN。"
#elif defined(ORIG_CHAMBER_AUTO_FAN_PIN)
  #error "ORIG_CHAMBER_AUTO_FAN_PIN现在只需CHAMBER_AUTO_FAN_PIN。"
#elif defined(HOMING_BACKOFF_MM)
  #error "HOMING_BACKOFF_MM现在称为HOMING_BACKOFF_POST_MM。"
#elif defined(X_HOME_BUMP_MM) || defined(Y_HOME_BUMP_MM) || defined(Z_HOME_BUMP_MM)
  #error "[XYZ]_HOME_BUMP_MM现在是HOMING_BUMP_MM。"
#elif defined(DIGIPOT_I2C)
  #error "DIGIPOT_I2C现在是DIGIPOT_MCP4451（或DIGIPOT_MCP4018）。"
#elif defined(TOUCH_BUTTONS)
  #error "TOUCH_BUTTONS现在称为TOUCH_SCREEN。"
#elif defined(LCD_FULL_PIXEL_HEIGHT) || defined(LCD_FULL_PIXEL_WIDTH)
  #error "LCD_FULL_PIXEL_(WIDTH|HEIGHT)已弃用，请将其删除。"
#elif defined(FSMC_UPSCALE)
  #error "FSMC_UPSCALE现在称为GRAPHICAL_TFT_UPSCALE。"
#elif defined(ANYCUBIC_TFT_MODEL)
  #error "ANYCUBIC_TFT_MODEL现在称为ANYCUBIC_LCD_I3MEGA。"
#elif defined(EVENT_GCODE_SD_STOP)
  #error "EVENT_GCODE_SD_STOP现在称为EVENT_GCODE_SD_ABORT。"
#elif defined(GRAPHICAL_TFT_ROTATE_180)
  #error "GRAPHICAL_TFT_ROTATE_180现在是将TFT_ROTATION设置为TFT_ROTATE_180。"
#elif defined(PROBE_OFFSET_START)
  #error "PROBE_OFFSET_START现在是PROBE_OFFSET_WIZARD_START_Z。"
#elif defined(POWER_LOSS_PULL)
  #error "POWER_LOSS_PULL现在是具体的POWER_LOSS_PULL(UP|DOWN)。"
#elif defined(SHORT_MANUAL_Z_MOVE)
  #error "SHORT_MANUAL_Z_MOVE现在是FINE_MANUAL_MOVE，在大多数打印机上适用于Z轴。"
#elif defined(FIL_RUNOUT_INVERTING)
  #if FIL_RUNOUT_INVERTING
    #error "FIL_RUNOUT_INVERTING为true现在是FIL_RUNOUT_STATE HIGH。"
  #else
    #error "FIL_RUNOUT_INVERTING为false现在是FIL_RUNOUT_STATE LOW。"
  #endif
#elif defined(ASSISTED_TRAMMING_MENU_ITEM)
  #error "ASSISTED_TRAMMING_MENU_ITEM已过时，请将其删除。"
#elif defined(UNKNOWN_Z_NO_RAISE)
  #error "UNKNOWN_Z_NO_RAISE被Z_IDLE_HEIGHT设置为Z_MAX_POS取代。"
#elif defined(Z_AFTER_DEACTIVATE)
  #error "Z_AFTER_DEACTIVATE被Z_IDLE_HEIGHT取代。"
#elif defined(MEATPACK)
  #error "MEATPACK通过MEATPACK_ON_SERIAL_PORT_1、MEATPACK_ON_SERIAL_PORT_2等启用。"
#elif defined(CUSTOM_USER_MENUS)
  #error "CUSTOM_USER_MENUS已被CUSTOM_MENU_MAIN和CUSTOM_MENU_CONFIG取代。"
#elif defined(MKS_LCD12864)
  #error "MKS_LCD12864现在是MKS_LCD12864A或MKS_LCD12864B。"
#elif defined(DOGM_SD_PERCENT)
  #error "DOGM_SD_PERCENT现在是SHOW_PROGRESS_PERCENT。"
#elif defined(NEOPIXEL_BKGD_LED_INDEX)
  #error "NEOPIXEL_BKGD_LED_INDEX现在是NEOPIXEL_BKGD_INDEX_FIRST。"
#elif defined(TEMP_SENSOR_1_AS_REDUNDANT)
  #error "TEMP_SENSOR_1_AS_REDUNDANT现在是TEMP_SENSOR_REDUNDANT，并带有相关的TEMP_SENSOR_REDUNDANT_*配置。"
#elif defined(MAX_REDUNDANT_TEMP_SENSOR_DIFF)
  #error "MAX_REDUNDANT_TEMP_SENSOR_DIFF现在是TEMP_SENSOR_REDUNDANT_MAX_DIFF"
#elif defined(LCD_ALEPHOBJECTS_CLCD_UI)
  #error "LCD_ALEPHOBJECTS_CLCD_UI现在是LCD_LULZBOT_CLCD_UI。"
#elif defined(MIN_ARC_SEGMENTS)
  #error "MIN_ARC_SEGMENTS现在是MIN_CIRCLE_SEGMENTS。"
#elif defined(ARC_SEGMENTS_PER_R)
  #error "ARC_SUPPORT不再使用ARC_SEGMENTS_PER_R。"
#elif ENABLED(ARC_SUPPORT) && (!defined(MIN_ARC_SEGMENT_MM) || !defined(MAX_ARC_SEGMENT_MM))
  #error "ARC_SUPPORT现在需要MIN_ARC_SEGMENT_MM和MAX_ARC_SEGMENT_MM。"
#elif defined(LASER_POWER_INLINE)
  #error "LASER_POWER_INLINE已过时。"
#elif defined(SPINDLE_LASER_PWM)
  #error "SPINDLE_LASER_PWM（true）现在通过启用SPINDLE_LASER_USE_PWM（enabled）设置。"
#elif ANY(IS_RAMPS_EEB, IS_RAMPS_EEF, IS_RAMPS_EFB, IS_RAMPS_EFF, IS_RAMPS_SF)
  #error "IS_RAMPS_*条件（用于加热器/风扇/加热床引脚）现在称为FET_ORDER_*。"
#elif defined(PROBE_TEMP_COMPENSATION)
  #error "PROBE_TEMP_COMPENSATION现在使用PTC_PROBE、PTC_BED、PTC_HOTEND选项进行设置。"
#elif defined(BTC_PROBE_TEMP)
  #error "BTC_PROBE_TEMP现在是PTC_PROBE_TEMP。"
#elif defined(LCD_SCREEN_ROT_90)
  #error "LCD_SCREEN_ROT_90现在是LCD_SCREEN_ROTATE，值为90。"
#elif defined(LCD_SCREEN_ROT_180)
  #error "LCD_SCREEN_ROT_180现在是LCD_SCREEN_ROTATE，值为180。"
#elif defined(LCD_SCREEN_ROT_270)
  #error "LCD_SCREEN_ROT_270现在是LCD_SCREEN_ROTATE，值为270。"
#elif defined(DEFAULT_LCD_BRIGHTNESS)
  #error "DEFAULT_LCD_BRIGHTNESS现在是LCD_BRIGHTNESS_DEFAULT。"
#elif defined(NOZZLE_PARK_X_ONLY)
  #error "NOZZLE_PARK_X_ONLY现在是NOZZLE_PARK_MOVE 1。"
#elif defined(NOZZLE_PARK_Y_ONLY)
  #error "NOZZLE_PARK_Y_ONLY现在是NOZZLE_PARK_MOVE 2。"
#elif defined(Z_STEPPER_ALIGN_KNOWN_STEPPER_POSITIONS)
  #error "Z_STEPPER_ALIGN_KNOWN_STEPPER_POSITIONS现在只需Z_STEPPER_ALIGN_STEPPER_XY。"
#elif defined(DWIN_CREALITY_LCD_ENHANCED)
  #error "DWIN_CREALITY_LCD_ENHANCED现在是DWIN_LCD_PROUI。"
#elif defined(LINEAR_AXES)
  #error "LINEAR_AXES现在是NUM_AXES（考虑到旋转轴）。"
#elif defined(X_DUAL_STEPPER_DRIVERS)
  #error "X_DUAL_STEPPER_DRIVERS不再需要，请将其删除。"
#elif defined(Y_DUAL_STEPPER_DRIVERS)
  #error "Y_DUAL_STEPPER_DRIVERS不再需要，请将其删除。"
#elif defined(NUM_Z_STEPPER_DRIVERS)
  #error "NUM_Z_STEPPER_DRIVERS不再需要，请将其删除。"
#elif defined(LEVEL_BED_CORNERS)
  #error "LEVEL_BED_CORNERS现在是LCD_BED_TRAMMING。"
#elif defined(LEVEL_CORNERS_INSET_LFRB) || defined(LEVEL_CORNERS_HEIGHT) || defined(LEVEL_CORNERS_Z_HOP) || defined(LEVEL_CORNERS_USE_PROBE) || defined(LEVEL_CORNERS_PROBE_TOLERANCE) || defined(LEVEL_CORNERS_VERIFY_RAISED) || defined(LEVEL_CORNERS_AUDIO_FEEDBACK)
  #error "LEVEL_CORNERS_*设置已重命名为BED_TRAMMING_*设置。"
#elif defined(LEVEL_CENTER_TOO)
  #error "LEVEL_CENTER_TOO现在是BED_TRAMMING_INCLUDE_CENTER。"
#elif defined(TOUCH_IDLE_SLEEP)
  #error "TOUCH_IDLE_SLEEP（秒）现在是TOUCH_IDLE_SLEEP_MINS（分钟）。"
#elif defined(LCD_BACKLIGHT_TIMEOUT)
  #error "LCD_BACKLIGHT_TIMEOUT（秒）现在是LCD_BACKLIGHT_TIMEOUT_MINS（分钟）。"
#elif defined(LCD_SET_PROGRESS_MANUALLY)
  #error "LCD_SET_PROGRESS_MANUALLY现在是SET_PROGRESS_MANUALLY。"
#elif defined(USE_M73_REMAINING_TIME)
  #error "USE_M73_REMAINING_TIME现在是SET_REMAINING_TIME。"
#elif defined(SHOW_SD_PERCENT)
  #error "SHOW_SD_PERCENT现在是SHOW_PROGRESS_PERCENT。"
#elif defined(LIN_ADVANCE_K)
  #error "LIN_ADVANCE_K现在是ADVANCE_K。"
#elif defined(EXTRA_LIN_ADVANCE_K)
  #error "EXTRA_LIN_ADVANCE_K现在是ADVANCE_K_EXTRA。"
#elif defined(POLAR_SEGMENTS_PER_SECOND) || defined(DELTA_SEGMENTS_PER_SECOND)  || defined(SCARA_SEGMENTS_PER_SECOND) || defined(TPARA_SEGMENTS_PER_SECOND)
  #error "(POLAR|DELTA|SCARA|TPARA)_SEGMENTS_PER_SECOND现在是DEFAULT_SEGMENTS_PER_SECOND。"
#elif defined(TMC_SW_MOSI) || defined(TMC_SW_MISO) || defined(TMC_SW_SCK)
  #error "TMC_SW_(MOSI|MISO|SCK)现在是TMC_SPI_(MOSI|MISO|SCK)。"
#elif ANY(DGUS_LCD_UI_ORIGIN, DGUS_LCD_UI_FYSETC, DGUS_LCD_UI_HIPRECY, DGUS_LCD_UI_MKS, DGUS_LCD_UI_RELOADED) && !defined(DGUS_LCD_UI)
  #error "DGUS_LCD_UI_[TYPE]现在使用DGUS_LCD_UI TYPE进行设置。"
#elif defined(DELTA_PRINTABLE_RADIUS)
  #error "DELTA_PRINTABLE_RADIUS现在是PRINTABLE_RADIUS。"
#elif defined(SCARA_PRINTABLE_RADIUS)
  #error "SCARA_PRINTABLE_RADIUS现在是PRINTABLE_RADIUS。"
#elif defined(SCARA_FEEDRATE_SCALING)
  #error "SCARA_FEEDRATE_SCALING现在是FEEDRATE_SCALING。"
#elif defined(MILLISECONDS_PREHEAT_TIME)
  #error "MILLISECONDS_PREHEAT_TIME现在是PREHEAT_TIME_HOTEND_MS。"
#elif defined(EXPERIMENTAL_SCURVE)
  #error "不再需要EXPERIMENTAL_SCURVE，请将其删除。"
#elif defined(BABYSTEP_ZPROBE_GFX_OVERLAY)
  #error "BABYSTEP_ZPROBE_GFX_OVERLAY现在是BABYSTEP_GFX_OVERLAY。"
#elif defined(DISABLE_INACTIVE_EXTRUDER)
  #error "DISABLE_INACTIVE_EXTRUDER现在是DISABLE_OTHER_EXTRUDERS。"
#elif defined(INVERT_X_STEP_PIN) || defined(INVERT_Y_STEP_PIN) || defined(INVERT_Z_STEP_PIN) || defined(INVERT_I_STEP_PIN) || defined(INVERT_J_STEP_PIN) || defined(INVERT_K_STEP_PIN) || defined(INVERT_U_STEP_PIN) || defined(INVERT_V_STEP_PIN) || defined(INVERT_W_STEP_PIN) || defined(INVERT_E_STEP_PIN)
  #error "INVERT_*_STEP_PIN为true现在是STEP_STATE_* LOW，INVERT_*_STEP_PIN为false现在是STEP_STATE_* HIGH。"
#elif defined(PROBE_PT_1_X) || defined(PROBE_PT_1_Y) || defined(PROBE_PT_2_X) || defined(PROBE_PT_2_Y) || defined(PROBE_PT_3_X) || defined(PROBE_PT_3_Y)
  #error "PROBE_PT_[123]_[XY]现在使用PROBE_PT_[123]和数组{x，y}进行定义。"
#elif defined(SQUARE_WAVE_STEPPING)
  #error "SQUARE_WAVE_STEPPING现在是EDGE_STEPPING。"
#elif defined(FAN_PIN)
  #error "FAN_PIN现在是FAN0_PIN。"
#elif defined(X_MIN_ENDSTOP_INVERTING) || defined(Y_MIN_ENDSTOP_INVERTING) || defined(Z_MIN_ENDSTOP_INVERTING) \
   || defined(I_MIN_ENDSTOP_INVERTING) || defined(J_MIN_ENDSTOP_INVERTING) || defined(K_MIN_ENDSTOP_INVERTING) \
   || defined(U_MIN_ENDSTOP_INVERTING) || defined(V_MIN_ENDSTOP_INVERTING) || defined(W_MIN_ENDSTOP_INVERTING) \
   || defined(X_MAX_ENDSTOP_INVERTING) || defined(Y_MAX_ENDSTOP_INVERTING) || defined(Z_MAX_ENDSTOP_INVERTING) \
   || defined(I_MAX_ENDSTOP_INVERTING) || defined(J_MAX_ENDSTOP_INVERTING) || defined(K_MAX_ENDSTOP_INVERTING) \
   || defined(U_MAX_ENDSTOP_INVERTING) || defined(V_MAX_ENDSTOP_INVERTING) || defined(W_MAX_ENDSTOP_INVERTING) \
   || defined(Z_MIN_PROBE_ENDSTOP_INVERTING)
  #error "*_ENDSTOP_INVERTING为false/true现在使用*_ENDSTOP_HIT_STATE为HIGH/LOW进行设置。"
#elif defined(DISABLE_INACTIVE_X) || defined(DISABLE_INACTIVE_Y) || defined(DISABLE_INACTIVE_Z) \
   || defined(DISABLE_INACTIVE_I) || defined(DISABLE_INACTIVE_J) || defined(DISABLE_INACTIVE_K) \
   || defined(DISABLE_INACTIVE_U) || defined(DISABLE_INACTIVE_V) || defined(DISABLE_INACTIVE_W) || defined(DISABLE_INACTIVE_E)
  #error "DISABLE_INACTIVE_[XYZIJKUVWE]现在是DISABLE_IDLE_[XYZIJKUVWE]。"
#elif defined(DEFAULT_STEPPER_DEACTIVE_TIME)
  #error "DEFAULT_STEPPER_DEACTIVE_TIME现在是DEFAULT_STEPPER_TIMEOUT_SEC。"
#elif defined(TFT_SHARED_SPI)
  #error "TFT_SHARED_SPI现在是TFT_SHARED_IO。"
#elif defined(LCD_PINS_ENABLE)
  #error "LCD_PINS_ENABLE现在是LCD_PINS_EN。"
#elif ANY(USE_XMIN_PLUG, USE_XMAX_PLUG, USE_YMIN_PLUG, USE_YMAX_PLUG, USE_ZMIN_PLUG, USE_ZMAX_PLUG, \
          USE_IMIN_PLUG, USE_IMAX_PLUG, USE_JMIN_PLUG, USE_JMAX_PLUG, USE_KMIN_PLUG, USE_KMAX_PLUG, \
          USE_UMIN_PLUG, USE_UMAX_PLUG, USE_VMIN_PLUG, USE_VMAX_PLUG, USE_WMIN_PLUG, USE_WMAX_PLUG)
  #error "USE_*_PLUG设置不再需要，应该删除。"
#elif defined(X2_USE_ENDSTOP)
  #error "X2_USE_ENDSTOP已过时。直接设置X2_STOP_PIN。（例如，'X2_USE_ENDSTOP _XMAX_'变为'X2_STOP_PIN X_MAX_PIN'）"
#elif defined(Y2_USE_ENDSTOP)
  #error "Y2_USE_ENDSTOP已过时。请直接设置Y2_STOP_PIN。例如，'Y2_USE_ENDSTOP _YMAX_'应改为'Y2_STOP_PIN Y_MAX_PIN'"
#elif defined(Z2_USE_ENDSTOP)
  #error "Z2_USE_ENDSTOP已过时。请直接设置Z2_STOP_PIN。例如，'Z2_USE_ENDSTOP _ZMAX_'应改为'Z2_STOP_PIN Z_MAX_PIN'"
#elif defined(Z3_USE_ENDSTOP)
  #error "Z3_USE_ENDSTOP已过时。请直接设置Z3_STOP_PIN。例如，'Z3_USE_ENDSTOP _ZMAX_'应改为'Z3_STOP_PIN Z_MAX_PIN'"
#elif defined(Z4_USE_ENDSTOP)
  #error "Z4_USE_ENDSTOP已过时。请直接设置Z4_STOP_PIN。例如，'Z4_USE_ENDSTOP _ZMAX_'应改为'Z4_STOP_PIN Z_MAX_PIN'"
#endif

// L64xx步进驱动器已被移除
#define _L6470              0x6470
#define _L6474              0x6474
#define _L6480              0x6480
#define _POWERSTEP01        0xF00D
#if HAS_DRIVER(L6470)
  #error "L6470步进驱动器在Marlin中不再受支持。"
#elif HAS_DRIVER(L6474)
  #error "L6474步进驱动器在Marlin中不再受支持。"
#elif HAS_DRIVER(L6480)
  #error "L6480步进驱动器在Marlin中不再受支持。"
#elif HAS_DRIVER(POWERSTEP01)
  #error "POWERSTEP01步进驱动器在Marlin中不再受支持。"
#endif
#undef _L6470
#undef _L6474
#undef _L6480
#undef _POWERSTEP01